#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : libxmlplusplus-3.2
Version  : 3.2
Release  : 2
URL      : https://github.com/GNOME/libxmlplusplus/archive/libxml++-3-2.zip
Source0  : https://github.com/GNOME/libxmlplusplus/archive/libxml++-3-2.zip
Summary  : C++ wrapper for libxml
Group    : Development/Tools
License  : LGPL-2.1
Requires: libxmlplusplus-3.2-lib = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : gettext-bin
BuildRequires : glibmm-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : libxml2-dev
BuildRequires : m4
BuildRequires : mm-common-dev
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(libxml-2.0)
Patch1: 0001-Disable-generating-documentation-from-autotools.patch

%description
libxml++
-------------
This library provides a C++ interface to XML files. It uses libxml2 to access
the XML files, and in order to configure libxml++ you must have both libxml2 and
pkg-config installed.

%package dev
Summary: dev components for the libxmlplusplus-3.2 package.
Group: Development
Requires: libxmlplusplus-3.2-lib = %{version}-%{release}
Provides: libxmlplusplus-3.2-devel = %{version}-%{release}
Requires: libxmlplusplus-3.2 = %{version}-%{release}

%description dev
dev components for the libxmlplusplus-3.2 package.


%package lib
Summary: lib components for the libxmlplusplus-3.2 package.
Group: Libraries

%description lib
lib components for the libxmlplusplus-3.2 package.


%package staticdev
Summary: staticdev components for the libxmlplusplus-3.2 package.
Group: Default
Requires: libxmlplusplus-3.2-dev = %{version}-%{release}

%description staticdev
staticdev components for the libxmlplusplus-3.2 package.


%prep
%setup -q -n libxmlplusplus-libxml-3-2
cd %{_builddir}/libxmlplusplus-libxml-3-2
%patch1 -p1

%build
## build_prepend content
find . -type f -name 'configure' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'configure.ac' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'libtool' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'libtool.m4' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name '*.m4' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
echo "AM_MAINTAINER_MODE([disable])" >> configure.ac
## build_prepend end
unset http_proxy
unset https_proxy
unset no_proxy
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1587281519
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
export FCFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
export FFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
export CFFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
export LDFLAGS="-O3 -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native "
export CXXFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -fvisibility-inlines-hidden -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
%autogen  --enable-static --enable-shared --disable-maintainer-mode
## make_prepend content
find . -type f -name 'Makefile' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'configure' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'configure.ac' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'libtool' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'libtool.m4' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name '*.m4' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'config.status' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
## make_prepend end
make  %{?_smp_mflags}  V=1 VERBOSE=1

%check
export LANG=C.UTF-8
unset http_proxy
unset https_proxy
unset no_proxy
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1587281519
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libxml++-3.0/libxml++/attribute.h
/usr/include/libxml++-3.0/libxml++/attributedeclaration.h
/usr/include/libxml++-3.0/libxml++/attributenode.h
/usr/include/libxml++-3.0/libxml++/document.h
/usr/include/libxml++-3.0/libxml++/dtd.h
/usr/include/libxml++-3.0/libxml++/exceptions/exception.h
/usr/include/libxml++-3.0/libxml++/exceptions/internal_error.h
/usr/include/libxml++-3.0/libxml++/exceptions/parse_error.h
/usr/include/libxml++-3.0/libxml++/exceptions/validity_error.h
/usr/include/libxml++-3.0/libxml++/exceptions/wrapped_exception.h
/usr/include/libxml++-3.0/libxml++/io/istreamparserinputbuffer.h
/usr/include/libxml++-3.0/libxml++/io/ostreamoutputbuffer.h
/usr/include/libxml++-3.0/libxml++/io/outputbuffer.h
/usr/include/libxml++-3.0/libxml++/io/parserinputbuffer.h
/usr/include/libxml++-3.0/libxml++/keepblanks.h
/usr/include/libxml++-3.0/libxml++/libxml++.h
/usr/include/libxml++-3.0/libxml++/nodes/cdatanode.h
/usr/include/libxml++-3.0/libxml++/nodes/commentnode.h
/usr/include/libxml++-3.0/libxml++/nodes/contentnode.h
/usr/include/libxml++-3.0/libxml++/nodes/element.h
/usr/include/libxml++-3.0/libxml++/nodes/entitydeclaration.h
/usr/include/libxml++-3.0/libxml++/nodes/entityreference.h
/usr/include/libxml++-3.0/libxml++/nodes/node.h
/usr/include/libxml++-3.0/libxml++/nodes/processinginstructionnode.h
/usr/include/libxml++-3.0/libxml++/nodes/textnode.h
/usr/include/libxml++-3.0/libxml++/nodes/xincludeend.h
/usr/include/libxml++-3.0/libxml++/nodes/xincludestart.h
/usr/include/libxml++-3.0/libxml++/noncopyable.h
/usr/include/libxml++-3.0/libxml++/parsers/domparser.h
/usr/include/libxml++-3.0/libxml++/parsers/parser.h
/usr/include/libxml++-3.0/libxml++/parsers/saxparser.h
/usr/include/libxml++-3.0/libxml++/parsers/textreader.h
/usr/include/libxml++-3.0/libxml++/relaxngschema.h
/usr/include/libxml++-3.0/libxml++/schemabase.h
/usr/include/libxml++-3.0/libxml++/validators/dtdvalidator.h
/usr/include/libxml++-3.0/libxml++/validators/relaxngvalidator.h
/usr/include/libxml++-3.0/libxml++/validators/schemavalidatorbase.h
/usr/include/libxml++-3.0/libxml++/validators/validator.h
/usr/include/libxml++-3.0/libxml++/validators/xsdvalidator.h
/usr/include/libxml++-3.0/libxml++/xsdschema.h
/usr/lib64/libxml++-3.0/include/libxml++config.h
/usr/lib64/pkgconfig/libxml++-3.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxml++-3.0.so
/usr/lib64/libxml++-3.0.so.1
/usr/lib64/libxml++-3.0.so.1.0.0

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libxml++-3.0.a
